[tool.isort]
line_length = 120
known_first_party = ["devogen-cli"]
multi_line_output = 3

[tool.yapf]
based_on_style = "google"
column_limit = 120
spaces_before_comment = 2
split_before_first_argument = "True"
split_all_top_level_comma_separated_values = "True"
coalesce_brackets = "True"